 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystemrev.panels.main_menu;

import schoolmanagementsystemrev.backend.JDBController;
/**
 *
 * @author lozan
*/

public class SignupPanel extends javax.swing.JPanel {

    
    public SignupPanel() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        signUpPanel = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        calltoAction_btn = new javax.swing.JButton();
        bottomLabel = new javax.swing.JLabel();
        signinPanel = new javax.swing.JPanel();
        signinLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        teacherBtn = new javax.swing.JToggleButton();
        studentBtn = new javax.swing.JToggleButton();
        parentBtn = new javax.swing.JToggleButton();
        signupBtn = new javax.swing.JButton();
        usnLabel = new javax.swing.JLabel();
        fullnLabel = new javax.swing.JLabel();
        addrLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 677));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        signUpPanel.setBackground(new java.awt.Color(153, 153, 255));
        signUpPanel.setMinimumSize(new java.awt.Dimension(500, 677));
        signUpPanel.setName(""); // NOI18N
        signUpPanel.setPreferredSize(new java.awt.Dimension(500, 677));
        signUpPanel.setLayout(new java.awt.GridBagLayout());

        topLabel.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        topLabel.setForeground(new java.awt.Color(255, 255, 255));
        topLabel.setText("Heya there!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        signUpPanel.add(topLabel, gridBagConstraints);

        calltoAction_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/login_btn.png"))); // NOI18N
        calltoAction_btn.setBorderPainted(false);
        calltoAction_btn.setContentAreaFilled(false);
        calltoAction_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calltoAction_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calltoAction_btnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        signUpPanel.add(calltoAction_btn, gridBagConstraints);

        bottomLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bottomLabel.setForeground(new java.awt.Color(255, 255, 255));
        bottomLabel.setText("Already have an account?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        signUpPanel.add(bottomLabel, gridBagConstraints);

        add(signUpPanel);

        signinPanel.setBackground(new java.awt.Color(204, 204, 255));
        signinPanel.setMinimumSize(new java.awt.Dimension(500, 677));
        signinPanel.setPreferredSize(new java.awt.Dimension(500, 677));
        signinPanel.setLayout(new java.awt.GridBagLayout());

        signinLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        signinLabel.setForeground(new java.awt.Color(255, 255, 255));
        signinLabel.setText("SIGN UP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 22, 0);
        signinPanel.add(signinLabel, gridBagConstraints);

        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        signinPanel.add(username, gridBagConstraints);

        address.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        address.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        signinPanel.add(address, gridBagConstraints);

        fullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fullname.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 9, 9);
        signinPanel.add(fullname, gridBagConstraints);

        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(9, 9, 0, 9);
        signinPanel.add(password, gridBagConstraints);

        teacherBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/teacherCh_btn.png"))); // NOI18N
        teacherBtn.setBorderPainted(false);
        teacherBtn.setContentAreaFilled(false);
        teacherBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        teacherBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/teacherCh_btn_isPressed.png"))); // NOI18N
        teacherBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/teacherCh_btn_isPressed.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        signinPanel.add(teacherBtn, gridBagConstraints);

        studentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/studentCh_Btn.png"))); // NOI18N
        studentBtn.setBorderPainted(false);
        studentBtn.setContentAreaFilled(false);
        studentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        studentBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/studentCh_btn_isPressed.png"))); // NOI18N
        studentBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/studentCh_btn_isPressed.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        signinPanel.add(studentBtn, gridBagConstraints);

        parentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/parentCh_btn.png"))); // NOI18N
        parentBtn.setBorderPainted(false);
        parentBtn.setContentAreaFilled(false);
        parentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        parentBtn.setPreferredSize(new java.awt.Dimension(100, 30));
        parentBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/parentCh_btn_isPressed.png"))); // NOI18N
        parentBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/parentCh_btn_isPressed.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        signinPanel.add(parentBtn, gridBagConstraints);

        signupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/signup_btn.png"))); // NOI18N
        signupBtn.setBorderPainted(false);
        signupBtn.setContentAreaFilled(false);
        signupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupBtn.setPreferredSize(new java.awt.Dimension(220, 40));
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(17, 17, 17, 17);
        signinPanel.add(signupBtn, gridBagConstraints);

        usnLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        usnLabel.setForeground(new java.awt.Color(255, 255, 255));
        usnLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        signinPanel.add(usnLabel, gridBagConstraints);

        fullnLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        fullnLabel.setForeground(new java.awt.Color(255, 255, 255));
        fullnLabel.setText("Full name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        signinPanel.add(fullnLabel, gridBagConstraints);

        addrLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addrLabel.setForeground(new java.awt.Color(255, 255, 255));
        addrLabel.setText("Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        signinPanel.add(addrLabel, gridBagConstraints);

        passLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        signinPanel.add(passLabel, gridBagConstraints);

        add(signinPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        JDBController connection = new JDBController();
        if(connection.toggleError(studentBtn, parentBtn, teacherBtn)){
            connection.toCreate(connection.toggleChoice(teacherBtn, studentBtn, parentBtn),username.getText(),address.getText(),fullname.getText(),password.getText());
        }
        else
            javax.swing.JOptionPane.showMessageDialog(this,"Something went wrong!");
            
    }//GEN-LAST:event_signupBtnActionPerformed

    private void calltoAction_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calltoAction_btnActionPerformed
        this.removeAll();
        this.repaint();
        this.revalidate();
        //Adding
        this.add(new SigninPanel());
        this.repaint();
        this.revalidate();
    }//GEN-LAST:event_calltoAction_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addrLabel;
    private javax.swing.JTextField address;
    private javax.swing.JLabel bottomLabel;
    private javax.swing.JButton calltoAction_btn;
    private javax.swing.JLabel fullnLabel;
    private javax.swing.JTextField fullname;
    private javax.swing.JToggleButton parentBtn;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JLabel signinLabel;
    private javax.swing.JPanel signinPanel;
    private javax.swing.JButton signupBtn;
    private javax.swing.JToggleButton studentBtn;
    private javax.swing.JToggleButton teacherBtn;
    private javax.swing.JLabel topLabel;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usnLabel;
    // End of variables declaration//GEN-END:variables
}
