/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystemrev.panels.dashboard_contents;

/**
 *
 * @author lozan
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    private String user;
    public DashboardPanel() {
        initComponents();
    }
    
    public void setUser(String username){
        user = username;
    }
    
    public String getUser(){
        return user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        profile_picture = new javax.swing.JLabel();
        usn = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        contentPanel_home = new javax.swing.JPanel();
        activities = new javax.swing.JButton();
        attendance = new javax.swing.JButton();
        classes = new javax.swing.JButton();
        grades = new javax.swing.JButton();
        profile = new javax.swing.JButton();
        forums = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 677));
        setPreferredSize(new java.awt.Dimension(1000, 677));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        sidePanel.setBackground(new java.awt.Color(153, 153, 255));
        sidePanel.setMaximumSize(new java.awt.Dimension(700, 32767));
        sidePanel.setPreferredSize(new java.awt.Dimension(200, 677));
        sidePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        profile_picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/add_icon.png"))); // NOI18N
        profile_picture.setToolTipText("");
        sidePanel.add(profile_picture);

        usn.setForeground(new java.awt.Color(255, 255, 255));
        usn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usn.setText("username");
        usn.setPreferredSize(new java.awt.Dimension(200, 16));
        usn.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        sidePanel.add(usn);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/home_btn.png"))); // NOI18N
        home.setToolTipText("");
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setPreferredSize(new java.awt.Dimension(150, 30));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        sidePanel.add(home);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/logout_btn.png"))); // NOI18N
        logout.setBorderPainted(false);
        logout.setContentAreaFilled(false);
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.setPreferredSize(new java.awt.Dimension(150, 30));
        logout.setVerifyInputWhenFocusTarget(false);
        sidePanel.add(logout);

        add(sidePanel);
        sidePanel.getAccessibleContext().setAccessibleName("");

        contentPanel_home.setBackground(new java.awt.Color(204, 204, 255));
        contentPanel_home.setPreferredSize(new java.awt.Dimension(700, 677));
        contentPanel_home.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 50, 25));

        activities.setBackground(new java.awt.Color(255, 255, 255));
        activities.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/dashboard_activities_btn.png"))); // NOI18N
        activities.setBorderPainted(false);
        activities.setContentAreaFilled(false);
        activities.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        activities.setPreferredSize(new java.awt.Dimension(250, 150));
        contentPanel_home.add(activities);

        attendance.setBackground(new java.awt.Color(255, 255, 255));
        attendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/dashboard_attendance_btn.png"))); // NOI18N
        attendance.setBorderPainted(false);
        attendance.setContentAreaFilled(false);
        attendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendance.setPreferredSize(new java.awt.Dimension(250, 150));
        contentPanel_home.add(attendance);

        classes.setBackground(new java.awt.Color(255, 255, 255));
        classes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/dashboard_class_btn.png"))); // NOI18N
        classes.setBorderPainted(false);
        classes.setContentAreaFilled(false);
        classes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classes.setPreferredSize(new java.awt.Dimension(250, 150));
        contentPanel_home.add(classes);

        grades.setBackground(new java.awt.Color(255, 255, 255));
        grades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/dashboard_grades_btn.png"))); // NOI18N
        grades.setBorderPainted(false);
        grades.setContentAreaFilled(false);
        grades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grades.setPreferredSize(new java.awt.Dimension(250, 150));
        contentPanel_home.add(grades);

        profile.setBackground(new java.awt.Color(255, 255, 255));
        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/dashboard_classmates_btn.png"))); // NOI18N
        profile.setBorderPainted(false);
        profile.setContentAreaFilled(false);
        profile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profile.setPreferredSize(new java.awt.Dimension(250, 150));
        contentPanel_home.add(profile);

        forums.setBackground(new java.awt.Color(255, 255, 255));
        forums.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystemrev/resources/icons/dashboard_classmates_btn.png"))); // NOI18N
        forums.setBorderPainted(false);
        forums.setContentAreaFilled(false);
        forums.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forums.setPreferredSize(new java.awt.Dimension(250, 150));
        contentPanel_home.add(forums);

        add(contentPanel_home);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
       
    }//GEN-LAST:event_homeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activities;
    private javax.swing.JButton attendance;
    private javax.swing.JButton classes;
    private javax.swing.JPanel contentPanel_home;
    private javax.swing.JButton forums;
    private javax.swing.JButton grades;
    private javax.swing.JButton home;
    private javax.swing.JButton logout;
    private javax.swing.JButton profile;
    private javax.swing.JLabel profile_picture;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel usn;
    // End of variables declaration//GEN-END:variables
}
